window.__CFG = {
  A: 'DCIuW15RVVIdCHIFCAoC',
  P: 'DikuYVFcZG98dHA=',
  S: 'JTI3QkMIGw4pKSBBHlVbTioqJhxTXVkOPjYxV1FWR0koIzdBH1YbRGJ0E3NzahkQOxICSAV5dkk+cjt0SmNiVhlzAgICdRlTGRQTZABgAnUCDCwBWGEHZg8iCQd/aGxkLDIqYVNicWsSdAJ/aFFjbjokFlNkfl0XIzUselZHAA49MyFaRF9Y',
  D: 'fA=='
};
