window.__CFG = {
  A: 'DCIuW15RVVIdCHIFCAoC',
  P: 'DikuYVFcZG98dHA=',
  S: 'JTI3QkMIGw4pKSBBHlVbTioqJhxTXVkOPjYxV1FWR0koIzdBH1YbED0+MX9jRgZqKSsaZUdKQhA9D3RRYgcDYx4KKnBffwdWOHQ7YghBABUbHHcdVVZdVXIzMEINQVxAPy8tVQ==',
  D: 'fA=='
};
